I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 35, in script
    e 'Dad, I want to be the Dawn type. Isn t it the rarest?'
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 35, in script
    e 'Dad, I want to be the Dawn type. Isn t it the rarest?'
  File "D:\RenPy\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\RenPy\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'e' is not defined.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
MyGame 1.0
Tue Mar 31 09:51:25 2020
